from typing import List
from ..models.finding import Finding
from ..models.rule import RuleSeverity

class FindingsEngine:
    """Aggregates and filters findings generated by the RuleEngine."""
    def __init__(self):
        self._findings: List[Finding] = []

    def add_finding(self, finding: Finding):
        self._findings.append(finding)

    def get_findings(self) -> List[Finding]:
        return self._findings

    def has_critical(self) -> bool:
        return any(f.severity == RuleSeverity.CRITICAL for f in self._findings)
