import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { getDomains, deleteDomain, createDomain } from '../lib/api';
import { BookTemplate, Trash2, Plus } from 'lucide-react';

export default function Domains() {
  const queryClient = useQueryClient();
  const { data: domains, isLoading } = useQuery({ queryKey: ['domains'], queryFn: getDomains });

  const deleteMutation = useMutation({
    mutationFn: deleteDomain,
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['domains'] })
  });

  const createMutation = useMutation({
    mutationFn: ({name, absolutePath}: {name: string, absolutePath?: string}) => createDomain(name, absolutePath),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['domains'] })
  });

  const handleDelete = (id: string) => {
    if (window.confirm(`Are you sure you want to delete domain ${id}?`)) {
      deleteMutation.mutate(id);
    }
  };

  const handleAdd = () => {
    const name = window.prompt("Enter new domain name:");
    if (!name) return;
    
    const absolutePath = window.prompt("Enter project folder absolute path (mandatory):");
    if (!absolutePath || absolutePath.trim() === "") {
      alert("Project folder absolute path is mandatory.");
      return;
    }
    
    createMutation.mutate({ name, absolutePath: absolutePath.trim() });
  };

  if (isLoading) return <div className="text-gray-500">Loading domains...</div>;

  return (
    <div>
      <div className="flex justify-between items-start mb-6">
        <div>
          <h1 className="text-3xl font-bold mb-2 text-gray-800">Domain Packages</h1>
          <p className="text-gray-600 max-w-3xl">
            This view is dynamically generated by the Python <code className="bg-gray-100 px-1 py-0.5 rounded text-sm">DomainRegistry</code> reading the actual 
            packages located in the <code className="bg-gray-100 px-1 py-0.5 rounded text-sm mx-1">governance/domains</code> directory.
          </p>
        </div>
        <button 
          onClick={handleAdd}
          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors"
        >
          <Plus className="w-4 h-4" /> Add Domain
        </button>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {domains?.map((d: any) => (
          <div key={d.id} className="bg-white rounded-lg shadow-sm border border-gray-100 p-6 flex flex-col h-full hover:shadow-md transition-shadow relative group">
            <div className="flex items-start justify-between mb-4">
              <div className="p-2 bg-blue-50 text-blue-600 rounded-lg">
                <BookTemplate className="w-6 h-6" />
              </div>
              <div className="flex items-center gap-2">
                <button 
                  onClick={() => handleDelete(d.id)}
                  className="opacity-0 group-hover:opacity-100 p-1.5 text-red-500 hover:bg-red-50 rounded transition-all"
                  title="Delete Domain"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
                <span className="px-2 py-1 rounded text-xs font-semibold bg-green-100 text-green-800">
                  {d.status}
                </span>
              </div>
            </div>
            
            <h3 className="text-lg font-bold text-gray-800 mb-1">{d.name}</h3>
            <p className="text-xs text-gray-500 font-mono mb-4">{d.id} • v{d.version || '1.0.0'}</p>
            
            <p className="text-sm text-gray-600 flex-grow">
              {d.description || "A registered domain blueprint containing standards, requirements, and permissions."}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}
