import { useQuery, useQueryClient } from '@tanstack/react-query';
import { getFindings, clearReports } from '../lib/api';
import { ShieldAlert, ShieldX, ShieldCheck, Info, Download, Trash2 } from 'lucide-react';

export default function Findings() {
  const queryClient = useQueryClient();
  const { data: findings, isLoading } = useQuery({ queryKey: ['findings'], queryFn: getFindings });

  const handleSaveData = () => {
    if (!findings) return;
    const blob = new Blob([JSON.stringify(findings, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `findings_history_${new Date().toISOString()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleClear = async () => {
    if (confirm("Are you sure you want to clear all execution history? This cannot be undone.")) {
      await clearReports();
      queryClient.invalidateQueries({ queryKey: ['findings'] });
      queryClient.invalidateQueries({ queryKey: ['reports'] });
    }
  };

  if (isLoading) return <div className="text-gray-500">Loading findings...</div>;

  const getSeverityIcon = (severity: string) => {
    switch(severity.toUpperCase()) {
      case 'CRITICAL': return <ShieldX className="text-red-500 w-5 h-5" />;
      case 'HIGH': return <ShieldAlert className="text-orange-500 w-5 h-5" />;
      case 'NORMAL': return <Info className="text-blue-500 w-5 h-5" />;
      case 'LOW': return <span className="text-purple-500 font-bold text-lg">✨</span>; // Sparkles for AI
      default: return <ShieldCheck className="text-green-500 w-5 h-5" />;
    }
  };

  const getSeverityBadgeClass = (severity: string) => {
    switch(severity.toUpperCase()) {
      case 'CRITICAL': return 'bg-red-50 text-red-700 border-red-200';
      case 'HIGH': return 'bg-orange-50 text-orange-700 border-orange-200';
      case 'NORMAL': return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'LOW': return 'bg-purple-50 text-purple-700 border-purple-200'; // Purple for AI
      default: return 'bg-gray-50 text-gray-700 border-gray-200';
    }
  };

  return (
    <div>
      <div className="flex justify-between items-start mb-6">
        <div>
          <h1 className="text-3xl font-bold mb-2 text-gray-800">Pipeline Findings</h1>
          <p className="text-gray-600 max-w-3xl">
            All architectural violations and findings generated by the agents during pipeline executions.
          </p>
        </div>
        
        {findings && findings.length > 0 && (
          <div className="flex space-x-3">
            <button
              onClick={handleSaveData}
              className="flex items-center space-x-1.5 px-3 py-1.5 bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 text-sm font-medium rounded shadow-sm transition-colors"
            >
              <Download className="w-4 h-4" />
              <span>Save</span>
            </button>
            <button
              onClick={handleClear}
              className="flex items-center space-x-1.5 px-3 py-1.5 bg-white border border-red-200 hover:bg-red-50 text-red-600 text-sm font-medium rounded shadow-sm transition-colors"
            >
              <Trash2 className="w-4 h-4" />
              <span>Clear</span>
            </button>
          </div>
        )}
      </div>

      {!findings || findings.length === 0 ? (
        <div className="bg-white p-8 rounded-lg shadow-sm border border-gray-100 text-center">
          <ShieldCheck className="w-12 h-12 text-green-400 mx-auto mb-3" />
          <h3 className="text-lg font-medium text-gray-900">No Findings</h3>
          <p className="text-gray-500 mt-1">Run an agent pipeline to generate findings.</p>
        </div>
      ) : (
        <div className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-200">
                <th className="p-4 font-semibold text-gray-600">Severity</th>
                <th className="p-4 font-semibold text-gray-600">Agent / Rule</th>
                <th className="p-4 font-semibold text-gray-600 w-1/3">Issue</th>
                <th className="p-4 font-semibold text-gray-600">Location</th>
                <th className="p-4 font-semibold text-gray-600">Pipeline / Target</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {findings.map((f: any) => (
                <tr key={f.id} className="hover:bg-gray-50 transition-colors group">
                  <td className="p-4">
                    <div className="flex items-center space-x-2">
                      {getSeverityIcon(f.severity)}
                      <span className={`text-xs font-bold px-2 py-1 rounded border ${getSeverityBadgeClass(f.severity)}`}>
                        {f.severity.toUpperCase()}
                      </span>
                    </div>
                  </td>
                  <td className="p-4">
                    <div className="font-medium text-gray-900">{f.agent_name || f.source?.agent}</div>
                    <div className="text-xs font-mono text-gray-500 mt-1">{f.source?.rule}</div>
                  </td>
                  <td className="p-4">
                    <div className="font-semibold text-gray-800">{f.title}</div>
                    <div className="text-sm text-gray-600 mt-1">{f.description}</div>
                    {f.recommendation && (
                      <div className="text-sm text-indigo-600 mt-2 bg-indigo-50 p-2 rounded">
                        <strong>Recommendation:</strong> {f.recommendation}
                      </div>
                    )}
                  </td>
                  <td className="p-4">
                    <div className="text-sm font-mono text-gray-700 bg-gray-100 px-2 py-1 rounded break-all">
                      {f.location?.file_path || 'N/A'}
                    </div>
                    {f.location?.start_line && (
                      <div className="text-xs text-gray-500 mt-1">Line {f.location.start_line}</div>
                    )}
                  </td>
                  <td className="p-4">
                    <div className="text-xs font-mono text-slate-500 bg-slate-100 px-2 py-1 rounded mb-1 inline-block">
                      {f.pipeline_id}
                    </div>
                    <div className="text-sm font-medium text-gray-700 break-all">{f.target_ref}</div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
