import { useQuery, useQueryClient } from '@tanstack/react-query';
import { getReports, clearReports } from '../lib/api';
import { CheckCircle2, AlertTriangle, XCircle, Clock, Download, Trash2 } from 'lucide-react';

export default function Reports() {
  const queryClient = useQueryClient();
  const { data: reports, isLoading } = useQuery({ queryKey: ['reports'], queryFn: getReports });

  const handleSaveData = () => {
    if (!reports) return;
    const blob = new Blob([JSON.stringify(reports, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reports_history_${new Date().toISOString()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleClear = async () => {
    if (confirm("Are you sure you want to clear all execution history? This cannot be undone.")) {
      await clearReports();
      queryClient.invalidateQueries({ queryKey: ['reports'] });
    }
  };

  if (isLoading) return <div className="text-gray-500">Loading reports...</div>;

  const getStatusIcon = (status: string) => {
    switch(status.toUpperCase()) {
      case 'PASS': return <CheckCircle2 className="text-green-500 w-6 h-6" />;
      case 'WARNING': return <AlertTriangle className="text-orange-500 w-6 h-6" />;
      case 'FAIL': return <XCircle className="text-red-500 w-6 h-6" />;
      default: return <Clock className="text-gray-500 w-6 h-6" />;
    }
  };

  const getStatusBadge = (status: string) => {
    switch(status.toUpperCase()) {
      case 'PASS': return 'bg-green-100 text-green-800';
      case 'WARNING': return 'bg-orange-100 text-orange-800';
      case 'FAIL': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <div>
      <div className="flex justify-between items-start mb-6">
        <div>
          <h1 className="text-3xl font-bold mb-2 text-gray-800">Pipeline Execution Reports</h1>
          <p className="text-gray-600 max-w-3xl">
            A historical log of all Master Reports generated by the Platform Orchestrator during governance execution chains.
          </p>
        </div>
        
        {reports && reports.length > 0 && (
          <div className="flex space-x-3">
            <button
              onClick={handleSaveData}
              className="flex items-center space-x-1.5 px-3 py-1.5 bg-white border border-gray-200 hover:bg-gray-50 text-gray-700 text-sm font-medium rounded shadow-sm transition-colors"
            >
              <Download className="w-4 h-4" />
              <span>Save</span>
            </button>
            <button
              onClick={handleClear}
              className="flex items-center space-x-1.5 px-3 py-1.5 bg-white border border-red-200 hover:bg-red-50 text-red-600 text-sm font-medium rounded shadow-sm transition-colors"
            >
              <Trash2 className="w-4 h-4" />
              <span>Clear</span>
            </button>
          </div>
        )}
      </div>

      {!reports || reports.length === 0 ? (
        <div className="bg-white p-8 rounded-lg shadow-sm border border-gray-100 text-center">
          <Clock className="w-12 h-12 text-gray-300 mx-auto mb-3" />
          <h3 className="text-lg font-medium text-gray-900">No Pipeline Runs</h3>
          <p className="text-gray-500 mt-1">Execute an agent pipeline to generate a Master Report.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {reports.map((report: any) => {
            const totalFindings = report.agent_reports.reduce((acc: number, rep: any) => acc + (rep.findings?.length || 0), 0);
            
            return (
              <div key={report.pipeline_id} className="bg-white p-5 rounded-lg shadow-sm border border-gray-100 flex flex-col md:flex-row md:items-center justify-between gap-4 transition-shadow hover:shadow-md">
                <div className="flex items-start space-x-4">
                  <div className="mt-1">{getStatusIcon(report.overall_status)}</div>
                  <div>
                    <div className="flex items-center space-x-3 mb-1">
                      <h3 className="text-lg font-bold text-gray-900">{report.pipeline_id}</h3>
                      <span className={`px-2 py-0.5 rounded text-xs font-bold ${getStatusBadge(report.overall_status)}`}>
                        {report.overall_status.toUpperCase()}
                      </span>
                    </div>
                    <div className="text-sm text-gray-500">
                      Target: <span className="font-mono text-gray-800 bg-gray-100 px-1 rounded">{report.target_ref}</span>
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center space-x-6">
                  <div className="text-center">
                    <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">Agents Run</p>
                    <p className="text-xl font-bold text-slate-700">{report.agent_reports.length}</p>
                  </div>
                  <div className="text-center">
                    <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">Total Findings</p>
                    <p className="text-xl font-bold text-slate-700">{totalFindings}</p>
                  </div>
                  <div className="text-center bg-gray-50 px-4 py-2 rounded-lg border border-gray-100">
                    <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-1">Quality Score</p>
                    <p className={`text-2xl font-bold ${report.technical_score >= 90 ? 'text-green-600' : report.technical_score >= 70 ? 'text-yellow-600' : 'text-red-600'}`}>
                      {report.technical_score !== undefined ? report.technical_score : 'N/A'}
                    </p>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
